# tasks file for kubeadm

#<---------------- Add K8s Repo   ----------------------------->
# Add kubernetes repo 
- name: Add k8s repo
  ansible.builtin.copy:
    src: /etc/ansible/roles/kubeadm/files/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

#<----------------   set SELinus to permissive  mode  -------->
- name: Set SE linux to permissive & disable swap 
  ansible.builtin.shell: |
    setenforce 0
    sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
    sudo swapoff -a

# <---------------- Install Container D --------------------------->
# containerD pre-req for netfilter & overlay
- name: (containerD pre-req) configure overlay & br_netfiler
  ansible.builtin.copy:
    src: /etc/ansible/roles/kubeadm/files/k8s.conf
    dest: /etc/modules-load.d/k8s.conf
    
# Container runtime requiremenrs
- name: (containerD re-req) Implement net filgter & overlay
  ansible.builtin.shell: |
    sudo modprobe overlay
    sudo modprobe br_netfilter 


# containerD pre-req - allow iptables to see bridged traffic
- name: (containerD pre-req) allow bridged traffic
  ansible.builtin.copy:
    src: /etc/ansible/roles/kubeadm/files/k8s-ip.conf
    dest: /etc/sysctl.d/k8s.conf

# Apply w/out reboot
- name: (containerD re-req) Apply bridge withpout reboot
  ansible.builtin.shell: sudo sysctl --system

# Install yum utils for managing yum repo
- name: Install yum-utils  
  ansible.builtin.package:
    name: yum-utils
    state: latest

# add docker repo to  our local yum repo list w/ yum config manager
- name: Add docker repo
  ansible.builtin.command: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo" 

# Install container d
- name: Install containerd
  ansible.builtin.package:
    name: containerd.io

#  remove config.toml we dont want cri disable 
- name:  Delete config.toml & enable CRI
  ansible.builtin.file:
    path: /etc/containerd/config.toml
    state: absent 

# replace 
- name: replace containerd config.toml
  ansible.builtin.copy:
    src: /etc/ansible/roles/kubeadm/files/config.toml
    dest: /etc/containerd/config.toml

# Restart containerd service 
- name: Restart containerd service
  ansible.builtin.service:
    name: containerd
    state: restarted


# Add kubernetes repo to yum for RHEL / non debian
- name: Add K8s to yum repo
  ansible.builtin.copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
  when: ansible_facts['os_family'] != "Debian"

# <---------------- Install kubeadm, kubelet & kubeadm --------------------------->
# Install kubeadm kubelet and kubectl
- name: Install kubeadm, kubelet and kubectl
  ansible.builtin.command: "yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes"

# <------------------ enable kubelet service --------------------------------->
- name: Enable kubelet service
  ansible.builtin.service:
    name: kubelet
    enabled: yes  

# <------------------ Start kubelet service --------------------------------->
- name: Start kubelet service
  ansible.builtin.service:
    name: kubelet
    state: started

