---
# tasks file for core-networking
#
# <--- Install Docker & Docker compose
- name: Install docker 
  ansible.builtin.apt:
    name: docker.io
    state: present

- name: Install docker compose
  ansible.builtin.apt:
    name: docker-compose
    state: present

- name: Enable docker svc 
  ansible.builtin.systemd:
    name: docker.io
    enabled: yes
    state: started

