---
# tasks file for core-networking
#
# <--- Install Docker & Docker compose
- name: Install docker 
  ansible.builtin.apt:
    name: docker.io
    state: latest
  notify: completed_install

- name: run handler
  meta: flush_handlers

- name: Install docker compose
  ansible.builtin.apt:
    name: docker-compose
    state: latest
  notify: completed_install 

- name: Create core networking directory
  ansible.builtin.file:
    path: /home/ansible/core-networking
    state: directory
    mode: '0755'
    owner: ansible
    group: ansible

- name: Copy docker compose files into core-networking directory
  ansible.builtin.copy:
    src: /* 
    dest: ~/
    owner: ansible
    group: ansible
    mode: '755'


