---
# handlers file for compose-deployment

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: /home/ansible/apps
    state: directory
    recurse: yes
    owner: ansible
    group: ansible
