---
# handlers file for compose-deployment

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: /home/ansible/apps
    state: directory
    recurse: yes
    owner: ansible
    group: ansible

- name: Extract folder name from the URL
  set_fact:
    app_folder: "{{ git_repo_url | regex_search('([^/]+)\\.git$', '\\1') }}"