---
# tasks file for core-networking
#

- name: Create apps directory if not present
  ansible.builtin.file:
    path: /home/ansible/apps
    state: directory
    mode: '0755'

- name: Clone docker compose app repo
  ansible.builtin.git:
    repo: "{{ git_repo_url }}"
    dest: /home/ansible/apps
  notify:
    - Recursively change ownership of a directory
    - Extract folder name from the URL

- name: Post download Steps
  meta: flush_handlers

- name: Deploy docker compose
  ansible.builtin.debug:
    msg: "{{ app_folder.stdout }}"

- name: Find all subdirectories in the target directory
  ansible.builtin.find:
    paths: /home/ansible/apps/{{ app_folder.stdout }}
    file_type: directory
  register: apps_to_deploy

- name: Apps path print
  ansible.builtin.debug:
    msg: "{{ apps_to_deploy.stdout }}"

# - name: Deploy each App in their subdirectory
#   ansible.builtin.command: 
#   args:
#     chdir: "{{ item.path }}"
#   loop: "{{ apps_to_deploy.files }}"
