---
# tasks file for core-networking
#
# <--- Install Docker & Docker compose
- name: Install Podman 
  ansible.builtin.apt:
    name: podman
    state: latest

- name: Install python3-pip 
  ansible.builtin.apt:
    name: python3-pip
    state: latest

- name: Install Podman compose
  ansible.builtin.pip:
    name: podman-compose
    executable: pip3

- name: Set CNI version from 1.0.0 to 0.4.0
  ansible.builtin.shell: sed -i 's/"cniVersion": "1.0.0"/"cniVersion": "0.4.0"/g' /etc/cni/net.d/root_default.conflist

- name: Verify Install
  ansible.builtin.shell: podman-compose --help