---
# tasks file for core-networking

# Update packages
- name: Update all packages
  ansible.builtin.apt:
    upgrade: yes

# <--- Install Docker & Docker compose
- name: Install Podman 
  ansible.builtin.apt:
    name: podman=4.9.3
    state: present

# <--- Install Docker & Docker compose
- name: Install Podman compose
  ansible.builtin.apt:
    name: podman-compose=1.0.6
    state: present

# - name: Install python3-pip 
#   ansible.builtin.apt:
#     name: python3-pip
#     state: latest

# - name: Install Podman compose
#   ansible.builtin.pip:
#     name: podman-compose
#     executable: pip3

# - name: Set CNI version from 1.0.0 to 0.4.0
#   ansible.builtin.shell: sed -i 's/"cniVersion": "1.0.0"/"cniVersion": "0.4.0"/g' /etc/cni/net.d/root_default.conflist

# - name: Verify Install
#   ansible.builtin.shell: podman-compose --help