---
# tasks file for kube-master

#<------- open ports --------->
- name: Open k8s ports for Master Node (6443 api-server)
  ansible.builtin.command: firewall-cmd --permanent --add-port=6443/tcp

#<------- open ports --------->
- name: Open k8s ports for Master Node (2378-2380 etcd)
  ansible.builtin.command: firewall-cmd --permanent --add-port=2379-2380/tcp

