# --- Install Compose ---

- hosts: docker
  become: true
  gather_facts: false
  roles:
    - install-compose

- hosts: adm-monit01
  become: true
  gather_facts: false
  vars:
    git_repo_url: "https://github.com/Shoetan-DevOps/adm-performance-compose.git"
  roles:
    - deploy-compose-app

