# --- Master Node ---
- name: Configure k8s
  hosts: kube
  become: false
  tasks:
    - name: Ensure util-linus
      apt:
        name: util-linux
        state: present
    
    - name: Disable swap temporarily
      shell: swappoff -a
      
    - name: Permanent Disable Swap from fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*\s+swap\s+)'
        replace: '# \1'

    - name: (containerD re-req) load br_netfilter (bridged traffic) & overlay (image layering) Modules
      shell: |
        sudo modprobe overlay
        sudo modprobe br_netfilter

    - name: make br_netfilter & overlay modules load on startup
      copy: 
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: '0644'
    
    - name: sysctl params for k8s networking
      copy: 
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        owner: root
        group: root
        mode: '0644'
        
    - name: Apply sysctl params without reboot
      shell: sysctl --system
      
    - name: Install containerD
      apt: 
        name: containerd
        state: present
        update_cache: yes
      
    - name: create /etc/containerd dir
      file:
        path: /etc/containerd
        state: directory
        owner: root
        group: root
        mode: '0755'
        
    - name: Generate containerd default config
      shell: containerd config default
      register: containerd_config
        
    - name: Write config to /etc/containerd/config.toml
      copy: 
        content: "{{ containerd_config.stdout }}"
        dest: /etc/containerd/config.toml
        owner: root
        group: root
        mode: '0644'
        
        
    
