# tasks file for kube-master


# <---------------- Install Container D --------------------------->
# Install yum utils for managing yum repo
- name: Install yum-utils  
  ansible.builtin.package:
    name: yum-utils

# add docker repo to  our local yum repo
- name: Add docker reoi
  ansible.builtin.yum_repository:
    name: docker
    description: Add docker repo
    baseurl: https://download.docker.com/rhel/docker-ce.repo


# Install container d
- name: Install containerd
  ansible.builtin.package:
    name: containerd.io


# Add kubernetes repo to yum for RHEL / non debian
- name: Add K8s to yum repo
  ansible.builtin.copy:
    src: kubernetes.repo
    dest: sudo tee /etc/yum.repos.d/kubernetes.repo
  when: ansible_facts['os_family'] != "Debian"


# Add kubernetes repo to yum for RHEL / non debian
#- name: set SELinus to permissive mode
#  become: yes
#  ansible.builtin.copy:
#    src: kubernetes.repo
#    dest: sudo tee /etc/yum.repos.d/kubernetes.repo
#  when: ansible_facts['os_family'] != "Debian"

