---
# handlers file for wireguard-client

- name: Reload sysctl config
  become: yes
  ansible.builtin.shell: sysctl -p /etc/sysctl.d/wireguard.conf

- name: Move Keys to wireguard homedir
  become: yes
  ansible.builtin.shell: |
    mv /home/ansible/wgclient.key /etc/wireguard/
    mv /home/ansible/wgclient.pub /etc/wireguard/

- name: Get WireGuard client Public key
  become: yes
  ansible.builtin.shell: cat /etc/wireguard/wgclient.pub
  register: wg_publickey

- name: Get WireGuard client private key
  become: yes
  ansible.builtin.shell: cat /etc/wireguard/wgclient.key
  register: wg_privatekey

- name: Get WireGuard server Public key
  become: yes
  ansible.builtin.shell: cat /etc/wireguard/wgserver.pub
  register: wgserver_pubkey
  delegate_to: "{{ wg_server_ip }}"

- name: Create wgs0.conf file
  become: yes
  ansible.builtin.template:
    src: templates/wgc0.j2
    dest: /etc/wireguard/wg0.conf

- name: Read file contents
  become: yes
  ansible.builtin.shell: cat /etc/wireguard/wg0.conf
  register: wg0_content

- name: Print wg0.conf
  ansible.builtin.debug:
    var: wg0_content.stdout

- name: Create peer for wg server
  set_fact:
    wg_peer: |
      # ------------------
      [Peer]
      PublicKey = {{ wg_publickey.stdout }} # Client Public Key
      AllowedIPs = {{ wgc_cidr }}.{{ host_index }}

- name: Concatenate peer to wgs0
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/wireguard/wg0.conf
    line: "{{ wg_peer }}"
    create: yes
  delegate_to: "{{ wg_server_ip }}"

- name: Start wireguard client interface
  become: yes
  ansible.builtin.command: wg-quick up wg0

- name: Restart wireguard server interface
  become: yes
  ansible.builtin.shell: |
    wg-quick down wg0
    wg-quick up wg0
  delegate_to: "{{ wg_server_ip }}"
  ignore_errors: yes